services:
  dotfiles:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotfiles
    command: sleep 1000000
    volumes:
      # not mounting anything ....
      - ./.config:/root/.config
