# TODO: set base path and interpolate to config dir
set -g default-terminal "screen-256color"


# TODO: move those configs to file
set -g escape-time 0 # fix delay
set-option -g repeat-time 0 # fix delay

source-file ~/.config/tmux/bindings.tmux.cfg

source-file ~/.config/tmux/plugins.tmux.cfg

# plugin configuration files
source-file ~/.config/tmux/plugins_cfgs/persist_session.tmux.cfg
source-file ~/.config/tmux/plugins_cfgs/dracula.tmux.cfg

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

